### ISSUE TITLE
If the elements in the table are less than necessary for the scroll to work, they disappear

### ISSUE THREAD

**Issue by vitalieGo** [wubostc/virtualized-table-for-antd#21]
if the elements in the table are less than necessary for the scroll to work, they disappear

**Comment by vitalieGo** [comment]
this problem appeared after the last update

**Comment by wubostc** [comment]
Thanks @vitalieGo .
Counld you please put your code to https://codesandbox.io? because I can't reproduce the problem.

**Comment by wubostc** [comment]
[fea6a0e](https://github.com/wubostc/virtualized-table-for-antd/commit/fea6a0e453e19830b73944f3cfd745610562409c) it may be able to solve your problem？

**Comment by vitalieGo** [comment]
Sorry for the long answer, Problems are still present but have changed a bit. I have a menu with tabs and when switching, the data in the table changes when I go through it for the first time, everything is fine but the next time the data is not rendered and errors appear in the console, version 5.5 works fine.
![Screenshot from 2019-11-27 13-05-57](https://user-images.githubusercontent.com/55831156/69718335-bf9e5980-1116-11ea-849e-0017f1f520c9.png)

**Comment by vitalieGo** [comment]
in to calc height I use scroll = { y: "calc(100vh - 300px)" } may be it is a problem

**Comment by wubostc** [comment]
Thanks @vitalieGo .
Please `debug: true`, and put it into your comment. I want to get more detailed debug info from you.

**Comment by wubostc** [comment]
I think you'd better use https://codesandbox.io to reproduce your problem.
It's also easy for me to debug. :-)

**Comment by wubostc** [comment]
> 
> 
> in to calc height I use scroll = { y: "calc(100vh - 300px)" } may be it is a problem

It shouldn't be... I think.

**Comment by wubostc** [comment]
did you get some warn in the console?

**Comment by wubostc** [comment]
@vitalieGo ,I have commited some patches, can you try it for your project? if you have any free time. :-)

**Comment by vitalieGo** [comment]
I check this now, the elements do not disappear, but now the height of the table is not accepted according to the number of elements, a stable height remains, and if I go to the tab with more elements than the previous one and wrap it around where there are fewer elements, the list length with more elements is remembered and I scroll the empty list and the scroll bar started to jump, there is no smooth scrolling

**Comment by wubostc** [comment]
Let me see how written your code.

**Comment by vitalieGo** [comment]
Sorry I can't share may code :( I will try later to reproduce it in https://codesandbox.io

**Comment by wubostc** [comment]
> 
> 
> Sorry I can't share may code :( I will try later to reproduce it in https://codesandbox.io

You finally use it.

**Comment by vitalieGo** [comment]
Now look better, but bug with scroll blank list still present and height of the table is not accepted according to the number of elements.

**Comment by wubostc** [comment]
> Now look better, but bug with scroll blank list still present and height of the table is not accepted according to the number of elements.

Okay, I will wait for you to reproduce this issue.

**Comment by wubostc** [comment]
@vitalieGo , I think I found your problems.

**Comment by liubinis86** [comment]
@wubostc I have the same problem as him. My table has 5 tabs. Tab1 has 20 rows data and Tab5 only has 3. When I change tab formTab1 toTab5 and go back to Tab1,my table`s height is wrong and the console `console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);` has been trigger

**Comment by wubostc** [comment]
@liubinis86 thx,
I have pushed the last commit it should solve your problem, and the related test file I'll add it later, maybe tonight?
(You can also try it with `git clone`  this package, then run `npm run build` finally, import it from the root directory where your git's repository with `git clone`)

**Comment by liubinis86** [comment]
@wubostc ohhhhhhhh.thx.the last commit is work for me！When will it be released to NPM？

**Comment by wubostc** [comment]
> 
> 
> @wubostc ohhhhhhhh.thx.the last commit is work for me！When will it be released to NPM？

It needs more testing. :-)

**Comment by liubinis86** [comment]
@wubostc hello.I update my package to 0.6.3, but it didn't fix this issue. But I clone this package and run build, import  files from the `lib`  folder into my project can resolve it. 
Can I get your QQ or WeChat or other contact information?My QQ is 1049385272

**Comment by liubinis86** [comment]
@wubostc I found that use this [commit](https://github.com/wubostc/virtualized-table-for-antd/commit/3d2e314c951939366a7148eeb38cfceb70b60dcd) can fix this issue, but the lastest commit can not fix it.

**Comment by wubostc** [comment]
only this commit [a291fac](https://github.com/wubostc/virtualized-table-for-antd/commit/a291fac2fc0610d1997b5cca75379f6fd576f6b3) changed `src/index.tsx`.
are you sure this commit a291fac cause your issue again?

**Comment by wubostc** [comment]
我醉了，我明明都测试过的，改成那两句断言应该没什么问题啊，你看你控制台有显示什么错误啊

**Comment by liubinis86** [comment]
就是切换的时候，提示你新增的那个断言（`console.assert(ctx.computed_h >= 0);`）的错误。我把你删除的`if (ctx.computed_h < 0) ctx.computed_h = 0;`加上了他才不会报错，且会重新计算高度

**Comment by liubinis86** [comment]
![切换tab报错](https://user-images.githubusercontent.com/25797951/70123364-7e292380-16ad-11ea-9298-bd6b4d9bc521.gif)

**Comment by ducchungtx** [comment]
I have the same issue with you @liubinis86 but it more than sometimes table rerender like an empty array when I change datasource.

**Comment by wubostc** [comment]
ohh, fu*k
commit before
```
isNaN(undefined)
true
```
commit after
```
Number.isNaN(undefined)
false
```
真实见鬼了！

**Comment by liubinis86** [comment]
@wubostc 问题还是存在呢老哥，我昨天发的gif你看了嘛？先在第一个tab滚到最下面，然后切换到数据较少的tab，就出现那个问题了

**Comment by wubostc** [comment]
> 
> 
> @wubostc 问题还是存在呢老哥，我昨天发的gif你看了嘛？先在第一个tab滚到最下面，然后切换到数据较少的tab，就出现那个问题了

你这个问题应该不存在的，我在我本地测试过的，你更新到最新版本了吗？

**Comment by liubinis86** [comment]
更新到0.6.4了，依然报错。我把你删除的`if (ctx.computed_h < 0) ctx.computed_h = 0`加上了他才不会报错，且会重新计算高度

**Comment by wubostc** [comment]
> 
> 
> 更新到0.6.4了，依然报错。我把你删除的`if (ctx.computed_h < 0) ctx.computed_h = 0`加上了他才不会报错，且会重新计算高度

这个理论上是不会出现负数的，可能哪里又有bug，我远程帮你看看？

**Comment by liubinis86** [comment]
> > 更新到0.6.4了，依然报错。我把你删除的`if (ctx.computed_h < 0) ctx.computed_h = 0`加上了他才不会报错，且会重新计算高度
> 
> 这个理论上是不会出现负数的，可能哪里又有bug，我远程帮你看看？

可以，加我QQ（1049385272）么大佬？

**Comment by wubostc** [comment]
@vitalieGo @ducchungtx @liubinis86 
Guys ,this issue has been solved in v0.7.0, and I have publised to NPM just now!

**Comment by wubostc** [comment]
> 
> 
> I check this now, the elements do not disappear, but now the height of the table is not accepted according to the number of elements, a stable height remains, and if I go to the tab with more elements than the previous one and wrap it around where there are fewer elements, the list length with more elements is remembered and I scroll the empty list and the scroll bar started to jump, there is no smooth scrolling

If you  go to the tab without Antd.Pagination, you need to call this func `VTScroll(id, { top, left })`
